In [12]:
#CSC420 Library Function Dictionary
import matplotlib.pyplot as plt
import numpy as np
a = np.array([[1, 4, 3],
              [2, 5, 2],
              [4, 0, 1]])
for i in range(1, 3):  
    for j in range(3):
        if j == 0:
            a[i, j] = a[i, j] + min(a[i - 1, j], a[i - 1, j + 1])
        elif j == 3 - 1:
            a[i, j] = a[i, j] + min(a[i - 1, j - 1], a[i - 1, j])
        else:
            a[i, j] = a[i, j] + min(a[i - 1, j - 1], a[i- 1, j], a[i - 1, j + 1])
print(a)

rows = 3
min_col = 1
sum_energy = a



[[1 4 3]
 [3 6 5]
 [7 3 6]]


In [ ]:
#1
a = np.array([[0, 1,-1],
              [2, 3, 6],
              [5, 10, 13]])
print(np.delete(a[0, :],0,0))
print('a',a[0:2,:])
print('b',a[:, :2])

[ 1 -1]
a [[ 0  1 -1]
 [ 2  3  6]]
b [[ 0  1]
 [ 2  3]
 [ 5 10]]


In [ ]:
# resize image
resized = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)

In [ ]:
# deleting kth position in a row
removed_matrix[i, :, :] = np.delete(b, k, axis=0)

#convert color
#img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
#convert color
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

#for dealing with image from [0., 1.] to [0,255]
img = img_as_float(img)


In [ ]:
#find eigenvalues
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
A = np.array([[1,0],[0,-2]])
print(A)
eigvals, eigvecs = la.eig(A)
print(eigvals)
#If we know that the eigenvalues are real numbers 
#(ie. if  is symmetric), then we can use the NumPy array method .real to convert the array of eigenvalues to real numbers:
eigvals = eigvals.real
print(eigvals)

[[ 1  0]
 [ 0 -2]]
[ 1.+0.j -2.+0.j]
[ 1. -2.]


In [ ]:
import numpy as np
a = np.array([[0, 1,-1],
              [2, 3, -6],
              [5, -20, 13]])
print(np.min(a)) # return the min in all directions

-20


In [ ]:
#copy energy matrix to sum_energy
  np.copyto(sum_energy, gradient)

def Find_seam_path(img, min_col, sum_energy):
  #Make the connected path with smallest sum of enery Black on orginal img
  rows, cols = img.shape[0:2]
  #make the points in the path black points (Back_Trace)
  #range(start, end(not included, step))
  for r in range(rows-1, -1, -1):    
    img[r,min_col] = [0,0,0]
    if r != 0:
      if min_col == 0:
        if sum_energy[r-1,min_col+1]< sum_energy[r-1,min_col]:
          min_col = min_col+1
        elif min_col == cols -1:
          if sum_energy[r-1,min_col-1]< sum_energy[r-1,min_col]:
            min_col = min_col-1
        else:
          if sum_energy[r-1,min_col-1]<sum_energy[r-1,min_col] and sum_energy[r-1,min_col-1] < sum_energy[r-1,min_col+1]:
            min_col = min_col -1
          elif sum_energy[r-1,min_col+1]<sum_energy[r-1,min_col] and sum_energy[r-1,min_col+1] < sum_energy[r-1,min_col-1]:
            min_col = min_col +1
  return img

In [ ]:
R = img[:,:,0] #!!!!!
  G = img[:,:,1]
  B = img[:,:,2]

#'depth' is 6 (CV_64F)\n","traceback":["\u001b[0;31m---------------------------------------------------------------------------
img = img.astype('float32')