In [3]:
import numpy as np
import numpy.linalg as la

#Matrices

### Simple matrix

In [4]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

Matrix shape is a tuple storing the number of size of each dimentions.
For 2D matrices, the order is always rows-columns.

In [5]:
m.shape

(2, 3)

In [6]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(m)

numpy.ndarray

In [8]:
n = np.array([
    [[1,2],[3,4]],
    [[1,2],[3,4]]
])
n.shape

(2, 2, 2)

### Special matrices

#### Identity

In [ ]:
np.eye(3, 3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Zeros

In [ ]:
np.zeros((3, 3))

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

#### Ones

In [ ]:
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

## Indexing

For two dimentional matrices, rows are dimention 0 and columns are dimention 1.

In [29]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
m[1, 2]

6

##Slicing

Use the : symbol to get all values across a dimention.

In [10]:
m[1, :]

array([4, 5, 6])

The : can also represent a range

In [33]:
m[ -2:, : ]

array([[4, 5, 6],
       [7, 8, 9]])

## Reshaping


Preserve the data, but change the shape of the matrix.

In [18]:
m = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
m.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

Reshape a matrix into a single row, figuring out the correct number of columns


In [19]:
m.reshape((1, -1))

array([[1, 2, 3, 4, 5, 6]])

In [20]:
f = m.reshape(-1)
f

array([1, 2, 3, 4, 5, 6])

In [ ]:
f.shape

(6,)

## Getting useful statistics

Specify dimension using the axis keyword.

Minimum and maximum values

In [ ]:
m

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
m.max(axis=1)

array([2, 4, 6])

<b>Mean, standard deviation, and variance</b>

In [ ]:
m.mean(axis=0)

array([ 3.,  4.])

In [ ]:
m.std(axis=0)

array([ 1.63299316,  1.63299316])

In [ ]:
m.var(axis=0)

array([ 2.66666667,  2.66666667])

## Operations on matrices

#### Element-wise

In [ ]:
a = np.array([
    [1, 2],
    [3, 4]
])

a + a

array([[2, 4],
       [6, 8]])

In [ ]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
a ** a

array([[  1,   4],
       [ 27, 256]])

#### Matrix multiplication

In [ ]:
np.dot(a,b)

array([[3, 3, 3],
       [7, 7, 7]])

In [ ]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [1, 1, 1], 
    [1, 1, 1]
])
a.dot(b)

array([[3, 3, 3],
       [7, 7, 7]])

##Common linear algebra operations



In [ ]:
import numpy.linalg as la

### Transpose

In [ ]:
m = np.array([
    [1, 2],
    [3, 4]
])
m.T

array([[1, 3],
       [2, 4]])

### Eigenvalues and eigenvectors

In [ ]:
evals, evects = la.eig(m)

In [ ]:
evals

array([-0.37228132,  5.37228132])

In [ ]:
evects

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [ ]:
m.dot(evects[:,0])

array([ 0.30697009, -0.21062466])

In [ ]:
evals[0] * evects[:,0]

array([ 0.30697009, -0.21062466])

### Singular value decomposition

In [ ]:
U, s, V = np.linalg.svd(m) 

### Other useful operations
* Determinant: `la.det(m)`
* Norm: `la.norm(m)`
* Inverse: `la.inv(m)`

# Vectors

A vector is a special case of a matrix, and has a single dimension.

In [ ]:
np.array([0.1, 0.3, 0.1, 0.5])

array([ 0.1,  0.3,  0.1,  0.5])

Comma after length unpacks the first and only element of the tuple into the variable

In [ ]:
p = np.array([0.1, 0.3, 0.1, 0.5])
length, = p.shape
length

4

## Filtering

In [ ]:
p > 0.4

array([False, False, False,  True], dtype=bool)

In [ ]:
p[p > 0.4]

array([ 0.5])

## Searching and sorting


In [ ]:
p.min()

0.10000000000000001

In [ ]:
p.max()

0.5

Index of the max value in the array

In [ ]:
p.argmax()

3

Sorting the values

In [ ]:
p.sort()
p

array([ 0.1,  0.1,  0.3,  0.5])

Getting the indeces that correspond to a sorted order of the elements

In [ ]:
p = np.array([0.1, 0.3, 0.1, 0.5])
p.argsort()

array([0, 2, 1, 3])

In [ ]:
events = np.array(['A', 'B', 'C', 'D'])

Suppose we have an array of events, and `p` defines the probability mass function for these event.

To get the two most likely events, we need to figure out the indices of the top two values.

Note: the fancy indexing `[::-1]` reverses the elements in the array using Python slice syntax (start : stop : step).

In [ ]:
i = p.argsort()[::-1]
i

array([3, 1, 2, 0])

Getting the top most probable event is easy now:

In [ ]:
events[i[:2]]

array(['D', 'B', 'C', 'A'],
      dtype='|S1')

# Working with data


###Loading data from a text file

Specify the delimiter: comma, tab, space, etc.

In [ ]:
path = 'sample_text'
# Create a text file
with open(path, 'w') as f:
    f.write('1, 2, 3')
np.genfromtxt(path, delimiter=',')

array([ 1.,  2.,  3.])

`genfromtxt` has a lot of useful optional ([arguments](http://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html) )

Allows to specify the datatype to load the data as, specify comment format, skipping headers, etc.

### Loading data from a Matlab file with scipy


In [ ]:
from scipy.io import loadmat
data = {}
loadmat(filename, data)

`data` is a now dictionary of variable name to data. If the Matlab dump contained a variable `D`, access it by `data['D']` 

### Dumping numpy data to file

In [ ]:
data = np.array([1, 2, 3])
np.save('numpy_data', data)

### Loading numpy data from file

In [ ]:
data = np.load('numpy_data.npy')
data

array([1, 2, 3])

In [ ]:
m2 = np.arange(9).reshape((3, 3))
m2.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])